[package]
name = "fastdup-store"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
hashbrown.workspace = true
bytes.workspace = true
blake3.workspace = true
crc32c.workspace = true
fastdup-format.workspace = true
libc.workspace = true
memmap2.workspace = true
rayon.workspace = true
rustix.workspace = true
zstd.workspace = true

[lints]
workspace = true
