[package]
name = "fastdup-appliance"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
blake3.workspace = true
fastdup-copy-metrics.workspace = true
fastdup-format.workspace = true
fastdup-io-uring = { path = "../fastdup-io-uring" }
fastdup-posix.workspace = true
fastdup-store.workspace = true
fastcdc.workspace = true
fuse3.workspace = true
hashbrown.workspace = true
rayon.workspace = true
rustix.workspace = true
tokio.workspace = true

[dev-dependencies]
fastdup-testkit = { path = "../fastdup-testkit" }

[lints]
workspace = true
