[package]
name = "fastdup-appliance"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
fastdup-format.workspace = true
fastdup-posix.workspace = true
fastdup-store.workspace = true
fuse3.workspace = true
tokio.workspace = true

[dev-dependencies]
fastdup-testkit = { path = "../fastdup-testkit" }

[lints]
workspace = true
