use std::fmt::Write as _;
use std::io::Write as _;
use std::path::{Path, PathBuf};
use std::process::Command;

use crate::{ShareSettings, SmbEncryption};

const REPOSITORY_MOUNT: &str = "/srv/fastdup/repository";
const MANAGED_SHARE_DIRECTORY: &str = ".fastdup-shares";

#[derive(Debug, thiserror::Error)]
pub enum SambaError {
    #[error("invalid SMB setting: {0}")]
    Invalid(String),
    #[error("SMB configuration I/O failed: {0}")]
    Io(#[from] std::io::Error),
    #[error("testparm rejected the generated configuration: {0}")]
    Validation(String),
    #[error("Samba reload failed: {0}")]
    Reload(String),
}

#[derive(Clone, Debug)]
pub struct SambaConfig {
    managed_file: PathBuf,
}

impl SambaConfig {
    #[must_use]
    pub fn new(managed_file: impl Into<PathBuf>) -> Self {
        Self {
            managed_file: managed_file.into(),
        }
    }

    pub fn render(shares: &[ShareSettings]) -> Result<String, SambaError> {
        let mut rendered =
            String::from("# Generated by fastdup-agent. Manual edits are overwritten.\n");
        for share in shares {
            validate_share(share)?;
            if !share.enabled {
                continue;
            }
            writeln!(&mut rendered, "\n[{}]", share.name).expect("String write cannot fail");
            writeln!(
                &mut rendered,
                "\tpath = {}",
                Self::share_path(share).display()
            )
            .expect("String write cannot fail");
            writeln!(&mut rendered, "\tcomment = {}", share.description)
                .expect("String write cannot fail");
            writeln!(&mut rendered, "\tbrowseable = {}", yes_no(!share.hidden))
                .expect("String write cannot fail");
            writeln!(&mut rendered, "\tread only = {}", yes_no(share.read_only))
                .expect("String write cannot fail");
            writeln!(&mut rendered, "\tguest ok = {}", yes_no(share.guest_access))
                .expect("String write cannot fail");
            writeln!(
                &mut rendered,
                "\tsmb encrypt = {}",
                match share.encryption {
                    SmbEncryption::Desired => "desired",
                    SmbEncryption::Required => "required",
                }
            )
            .expect("String write cannot fail");
            writeln!(
                &mut rendered,
                "\taccess based share enum = {}",
                yes_no(share.access_based_enumeration)
            )
            .expect("String write cannot fail");
            let principals = share
                .allowed_users
                .iter()
                .cloned()
                .chain(share.allowed_groups.iter().map(|group| format!("@{group}")))
                .collect::<Vec<_>>();
            if !principals.is_empty() {
                writeln!(&mut rendered, "\tvalid users = {}", principals.join(" "))
                    .expect("String write cannot fail");
            }
            rendered.push_str(
                "\tvfs objects = fastdup\n\tfastdup:enabled = yes\n\tfastdup:clone alignment = 65536\n\tfastdup:maximum clone bytes = 1073741824\n",
            );
        }
        Ok(rendered)
    }

    #[must_use]
    pub fn share_path(share: &ShareSettings) -> PathBuf {
        Path::new(REPOSITORY_MOUNT)
            .join(MANAGED_SHARE_DIRECTORY)
            .join(&share.id)
    }

    pub fn apply(&self, shares: &[ShareSettings]) -> Result<(), SambaError> {
        let rendered = Self::render(shares)?;
        let parent = self.managed_file.parent().ok_or_else(|| {
            SambaError::Invalid("managed Samba file has no parent directory".to_owned())
        })?;
        std::fs::create_dir_all(parent)?;
        let stage = stage_path(&self.managed_file);
        let mut file = std::fs::OpenOptions::new()
            .create(true)
            .truncate(true)
            .write(true)
            .open(&stage)?;
        file.write_all(rendered.as_bytes())?;
        file.sync_all()?;
        let validation = Command::new("testparm")
            .args(["-s", "--suppress-prompt"])
            .arg(&stage)
            .output()?;
        if !validation.status.success() {
            let _ = std::fs::remove_file(&stage);
            return Err(SambaError::Validation(
                String::from_utf8_lossy(&validation.stderr)
                    .trim()
                    .to_owned(),
            ));
        }
        let backup = self.managed_file.with_extension("conf.previous");
        if self.managed_file.exists() {
            std::fs::copy(&self.managed_file, &backup)?;
        }
        std::fs::rename(&stage, &self.managed_file)?;
        sync_directory(parent)?;
        if shares.iter().any(|share| share.enabled) {
            let start = Command::new("systemctl")
                .args(["enable", "--now", "smb.service"])
                .output()?;
            if !start.status.success() {
                if backup.exists() {
                    std::fs::rename(&backup, &self.managed_file)?;
                    sync_directory(parent)?;
                }
                return Err(SambaError::Reload(
                    String::from_utf8_lossy(&start.stderr).trim().to_owned(),
                ));
            }
        } else {
            let active = Command::new("systemctl")
                .args(["is-active", "--quiet", "smb.service"])
                .status()?;
            if !active.success() {
                let _ = std::fs::remove_file(backup);
                return Ok(());
            }
        }
        let reload = Command::new("smbcontrol")
            .args(["all", "reload-config"])
            .output()?;
        if !reload.status.success() {
            if backup.exists() {
                std::fs::rename(&backup, &self.managed_file)?;
                sync_directory(parent)?;
                let _ = Command::new("smbcontrol")
                    .args(["all", "reload-config"])
                    .output();
            }
            return Err(SambaError::Reload(
                String::from_utf8_lossy(&reload.stderr).trim().to_owned(),
            ));
        }
        let _ = std::fs::remove_file(backup);
        Ok(())
    }

    pub fn close_share(name: &str) -> Result<(), SambaError> {
        validate_token(name, "Freigabename")?;
        let output = Command::new("smbcontrol")
            .args(["all", "close-share", name])
            .output()?;
        if output.status.success() {
            Ok(())
        } else {
            Err(SambaError::Reload(
                String::from_utf8_lossy(&output.stderr).trim().to_owned(),
            ))
        }
    }
}

fn validate_share(share: &ShareSettings) -> Result<(), SambaError> {
    validate_token(&share.id, "Freigabe-ID")?;
    validate_token(&share.name, "Freigabename")?;
    validate_line(&share.description, "Beschreibung")?;
    if share
        .logical_quota
        .is_some_and(|capacity| !capacity.is_valid())
    {
        return Err(SambaError::Invalid(
            "Logische Share-Quota muss zwischen 1 und 999 GB, TB oder PB liegen".to_owned(),
        ));
    }
    for user in &share.allowed_users {
        validate_token(user, "Benutzer")?;
    }
    for group in &share.allowed_groups {
        validate_token(group, "Gruppe")?;
    }
    Ok(())
}

fn validate_token(value: &str, label: &str) -> Result<(), SambaError> {
    if value.is_empty()
        || matches!(value, "." | "..")
        || value.len() > 80
        || !value
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'_' | b'-' | b'.' | b'$'))
    {
        return Err(SambaError::Invalid(format!(
            "{label} enthält nicht erlaubte Zeichen"
        )));
    }
    Ok(())
}

fn validate_line(value: &str, label: &str) -> Result<(), SambaError> {
    if value.len() > 160 || value.contains(['\n', '\r', '[', ']']) {
        return Err(SambaError::Invalid(format!("{label} ist ungültig")));
    }
    Ok(())
}

const fn yes_no(value: bool) -> &'static str {
    if value { "yes" } else { "no" }
}

fn stage_path(path: &Path) -> PathBuf {
    path.with_extension("conf.staged")
}

fn sync_directory(path: &Path) -> Result<(), std::io::Error> {
    std::fs::File::open(path)?.sync_all()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn share() -> ShareSettings {
        ShareSettings {
            id: "one".to_owned(),
            revision: 1,
            name: "backup".to_owned(),
            description: "FastDup Backup".to_owned(),
            enabled: true,
            hidden: true,
            read_only: false,
            guest_access: false,
            encryption: SmbEncryption::Required,
            access_based_enumeration: true,
            allowed_users: vec!["backup-operator".to_owned()],
            allowed_groups: vec!["storage_admins".to_owned()],
            logical_quota: Some(crate::LogicalQuota {
                value: 25,
                unit: crate::CapacityUnit::Tb,
            }),
        }
    }

    #[test]
    fn renders_the_fixed_fastdup_profile_and_safe_settings() {
        let rendered = SambaConfig::render(&[share()]).expect("render share");
        assert!(rendered.contains("[backup]"));
        assert!(rendered.contains("path = /srv/fastdup/repository/.fastdup-shares/one"));
        assert!(rendered.contains("browseable = no"));
        assert!(rendered.contains("smb encrypt = required"));
        assert!(rendered.contains("valid users = backup-operator @storage_admins"));
        assert!(rendered.contains("fastdup:clone alignment = 65536"));
    }

    #[test]
    fn rejects_configuration_injection() {
        let mut malicious = share();
        malicious.name = "backup]\n[root".to_owned();
        assert!(matches!(
            SambaConfig::render(&[malicious]),
            Err(SambaError::Invalid(_))
        ));

        let mut traversal = share();
        traversal.enabled = false;
        traversal.id = "..".to_owned();
        assert!(matches!(
            SambaConfig::render(&[traversal]),
            Err(SambaError::Invalid(_))
        ));
    }
}
