[package]
name = "fastdup-posix"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bytes.workspace = true
fastdup-copy-metrics.workspace = true
fuse3.workspace = true
futures-util.workspace = true
libc.workspace = true
tokio.workspace = true

[dev-dependencies]
rustix.workspace = true

[lints]
workspace = true
