d /etc/fastdup 0750 root fastdup-control -
d /run/fastdup 0770 root fastdup-control -
d /srv/fastdup 0750 root fastdup-control -
d /srv/fastdup/repository 0770 root fastdup-control -
d /var/lib/fastdup/repository 0750 root fastdup-control -
d /var/lib/fastdup/repository/metadata 0770 root fastdup-control -
d /var/lib/fastdup/repository/data 0770 root fastdup-control -
